src/lib/outputProcessor/resourceMerger.js, src/lib/outputProcessor/resourceMerger.spec.js
Fixes resource.meta type for merge op
Addresses [issue #72987] : Few resources are created without request details.
Manually tested.
=> fix resource.meta type

src/lib/handlebars-converter/handlebars-helpers.js, src/lib/handlebars-converter/handlebars-helpers.spec.js
Add math helper functions
Addresses [issue #71948].
Unit tests for all math helper functions added.
=> Add math helpers

package-lock.json, package.json
Update the packages for component governance.
Manually testing for basic operations.
=> update packages for comp gov warnings

src/static/js/template-editor.js
Sets codemirror mode based on data type
Addresses Bug 74416: Codemirror mode not changing between data types
Manual testing
=> Fix codemirror mode

src/lib/handlebars-converter/handlebars-helpers.js, src/lib/handlebars-converter/handlebars-helpers.spec.js
Support the datetime with the time zone information (Format: YYYY[MM[DD[HH[MM[SS[.S[S[S[S]]]]]]]]][+/-ZZZZ].)
Update the bad input handling according to the spec in http://www.hl7.eu/refactored/dtDTM.html
Add some test cases
=> Update the bad input handling

README.md, deploy/default-azuredeploy.json
Changes the deployment template to target a specific image instead of latest.
Addresses Bug 74582: UI of old installations getting updated automatically.
Ran deployment and confirmed version that was deployed.
=> Deploy specific image

src/templates/hl7v2/Resources/Patient.hbs, src/templates/hl7v2/Resources/RelatedPerson.hbs
iterate over multiple ids in PID/NK1 segments.
Addresses [issue #47 ].
Manually tested that repro msg gets parsed.
=> iterate over PID and NK1 ids

src/templates/cda/DataType/Identifier.hbs
Describe the changes in this PR.
=> Handling CDA nullFlavor in Identifiers

README.md, docs/helper-functions-summary.md, src/e2e-test/regression-test/util/interceptors.js, src/e2e-test/regression-test/util/interceptors.spec.js, src/lib/handlebars-converter/handlebars-helpers.js, src/lib/handlebars-converter/handlebars-helpers.spec.js
Added "generateUUIDV2" helper function.
See "handlebars-helper.spec.js".
=> Personal/xiatia/generate UUID v2

src/static/js/template-editor.js
Fixed issue #69 
Addresses #69
=> 2020.09.21 fixed issue#69 by updating related functions

src/templates/hl7v2/ADT_A01.hbs, src/templates/hl7v2/OML_O21.hbs, src/templates/hl7v2/ORU_R01.hbs, src/templates/hl7v2/Resources/Encounter.hbs, src/templates/hl7v2/Resources/Location.hbs, src/templates/hl7v2/Resources/PractitionerRole.hbs, src/templates/hl7v2/Resources/Procedure.hbs, src/templates/hl7v2/VXU_V04.hbs, test/e2e-test/regression-test/data/hl7v2/ADT_A01.hbs/ADT_A01.hbs-ADT01-23.hl7.json, test/e2e-test/regression-test/data/hl7v2/ADT_A01.hbs/ADT_A01.hbs-ADT01-28.hl7.json
This PR is mean to fix the "location(reference)" property missing in Encounter.hbs issue.   
Update the template and validate the generated data in test folder
=> Fix missing loactaion in Encounter.hbs and validate the data in test

README.md, docs/FiltersSummary.md, docs/SnippetConcept.md
Describe the changes in this PR.
=> Added documentation differentiating the two engines

README.md, docs/README.md, docs/api-summary.md, docs/convert-data-concept.md, docs/helper-functions-summary.md, docs/partial-template-concept.md, docs/template-creation-guide-CCDA.md, docs/template-creation-guide-HL7v2.md, docs/template-creation-how-to-guide.md, docs/using-helpers-concept.md, docs/web-ui-auto-update-issue.md, docs/web-ui-summary.md
Describe the changes in this PR.
=> Added documentation alert for Handlebars engine

src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/RuleBasedTests.cs
Added message verbosing mechanism for Java validator.
Outputting implementation is referenced from [here](https://xunit.net/docs/capturing-output).
All tests are passed.
=> 2020.11.12 finished validator checking messages verbosing mechanism

release.yml
=> [DotLiquid] Update build pipeline

Dockerfile
Using multistage build for the docker image the size should be much smaller. 
The new size is 237 Mb from 1.2Gb
none
There should be no
=> optimize docker image size

release.yml
=> [DotLiquid] Update version to v3

release.yml, src/Microsoft.Health.Fhir.Liquid.Converter.Tool/Microsoft.Health.Fhir.Liquid.Converter.Tool.nuspec, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.Liquid.Converter.nuspec
add functional tests in build pipeline
=> add functional tests in build pipeline

src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/Constants.cs, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/FunctionalTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests.csproj, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/RuleBasedTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Constants.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/EvaluateTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Hl7v2ProcessorTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Hl7v2TemplateProviderTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Microsoft.Health.Fhir.Liquid.Converter.UnitTests.csproj
Update tests of converter engine to run both locally and in build pipeline.
=> [DotLiquid] Update tests of converter engine

README.md
Describe the changes in this PR.
=> Added -data details

README.md, docs/api-summary.md, docs/template-creation-how-to-guide.md, docs/web-ui-summary.md, src/static/index.html
* Removed the git menu function, while keeping the internal functions.
* Updated related documents by removing git related sections.
All tests are passed.
=> 2020.12.14 hided git menu, removed related document descriptions

release.yml
=> [DotLiquid] Update version to v3.1

src/Microsoft.Health.Fhir.Liquid.Converter.Tool/TemplateManagementLogicHandler.cs
=> fix bug for pull templates CLI

src/Microsoft.Health.Fhir.Liquid.Converter.Tool/Models/PullTemplateOptions.cs, src/Microsoft.Health.Fhir.Liquid.Converter.Tool/Models/PushTemplateOptions.cs, src/Microsoft.Health.Fhir.TemplateManagement/Models/TemplateLayer.cs
fix typo and refine commandline description
=> refine CLI options and fix typo

data/Templates/Hl7v2/Resource/_Device.liquid, data/Templates/Hl7v2/Resource/_Immunization.liquid, data/Templates/Hl7v2/Resource/_Location.liquid, data/Templates/Hl7v2/Resource/_Organization.liquid, data/Templates/Hl7v2/Resource/_Patient.liquid, data/Templates/Hl7v2/Resource/_Practitioner.liquid, data/Templates/Hl7v2/Resource/_PractitionerRole.liquid, data/Templates/Hl7v2/Resource/_RelatedPerson.liquid, data/Templates/Hl7v2/Resource/_Specimen.liquid, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-28-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-251-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-28-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/OML_O21/MDHHS-OML-O21-1-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/OML_O21/MDHHS-OML-O21-2-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LAB-ORU-1-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LAB-ORU-2-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LRI_2.0-NG_CBC_Typ_Message-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/ORU-R01-RMGEAD-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/VXU_V04/IZ_1_1.1_Admin_Child_Max_Message-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/VXU_V04/VXU-expected.json
* Handled part of repeatable(in V2 while not in FHIR) identifiers, only take the first non-empty element.
=> Handle the repeatable identifiers

src/Microsoft.Health.Fhir.Liquid.Converter.Tool/TemplateManagementLogicHandler.cs, src/Microsoft.Health.Fhir.TemplateManagement.FunctionalTests/FunctionalTests.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Client/OrasClientTests.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/OCIFileManagerTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/Client/OrasClient.cs
Fix bug : folder contains space.
=> fix space in folder name and add tests

src/Microsoft.Health.Fhir.TemplateManagement.FunctionalTests/FunctionalTests.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Client/OrasClientTests.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/ImageInfoTest.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/OCIFileManagerTests.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/TemplateCollectionProviderFactoryTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/Models/ImageInfo.cs, src/Microsoft.Health.Fhir.TemplateManagement/OCIFileManager.cs
Add image name format validation: ^([a-z0-9])+((\.{1}|\-+|_{1,2})[a-z0-9]+)*$
=> add image name validation

docs/TemplateManagementCLI.md
update template management doc
=> Update template management doc

data/Templates/Hl7v2/Resource/_Observation.liquid, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests.csproj, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/RuleBasedTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/ORU-R01-RMGEAD-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter/Microsoft.Health.Fhir.Liquid.Converter.csproj
* Added FHIR parser functional tests, using all sample data as testing source.
* Removed `valueRange` property from `Resource/Observation` since it can't pass parser checking.
* Updated related test resources.
=> Added FHIR parser functional tests.

release.yml
=> Update version to 3.4

release.yml
=> upgrade version to 3.5

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Filters/DateFiltersTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Filters/DateFilters.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Models/FhirConverterErrorCode.cs, src/Microsoft.Health.Fhir.Liquid.Converter/OutputProcessor/PostProcessor.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Resources.Designer.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Resources.resx
=> Add support for time zone (#222)

data/Templates/Hl7v2/ADT_A01.liquid, data/Templates/Hl7v2/OML_O21.liquid, data/Templates/Hl7v2/ORU_R01.liquid, data/Templates/Hl7v2/Resource/_Provenance.liquid, data/Templates/Hl7v2/VXU_V04.liquid, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/FunctionalTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/RuleBasedTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-28-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-251-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-28-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/OML_O21/MDHHS-OML-O21-1-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/OML_O21/MDHHS-OML-O21-2-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LAB-ORU-1-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LAB-ORU-2-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LRI_2.0-NG_CBC_Typ_Message-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/ORU-R01-RMGEAD-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/VXU_V04/IZ_1_1.1_Admin_Child_Max_Message-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/VXU_V04/VXU-expected.json, src/Microsoft.Health.Fhir.TemplateManagement.FunctionalTests/TemplateCollectionFunctionalTests.cs
* According to previous discussion, we decide to add version number and disclaimer text in Provenance resource.
* Updated related testing resources.
=> Add template version number and disclaimer into Provenance resource

data/Templates/Hl7v2/Resource/_Provenance.liquid, release.yml, src/Microsoft.Health.Fhir.TemplateManagement.FunctionalTests/TemplateCollectionFunctionalTests.cs
* Add `TEMPLATE_VERSION_PLACEHOLDER` to `Resource/Provenance` resource.
* Inject template version number by replacing `TEMPLATE_VERSION_PLACEHOLDER` with `$(major).$(minor)` in pipeline.
=> Add template version number automatical injection functionality

.github/workflows/dockerimage.yml, Dockerfile, deploy/default-azuredeploy.json, package-lock.json, package.json
Upgrade handlebars version to 2.1.1.
=> Upgrade handlebars version to 2.1.1

src/Microsoft.Health.Fhir.TemplateManagement.FunctionalTests/TemplateCollectionFunctionalTests.cs
Functional tests are skipped in pipeline since ACR is not available. But some tests failed when I correctly setup ACR locally.
I modified these failed tests, and enable some of  functional tests which not use ACR. ( e.g. default templates tests)
=> Update functional tests for default templates

release.yml
Fix host image from windows-latest to windows-2019.
=> Update pipeline win host version

package-lock.json, package.json
* Upgrade `minimist` from 1.2.5 to 1.2.6
=> Upgrade vulnerable packages to latest version

release.yml, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.Liquid.Converter.nuspec
* update dotliquid version in nuget spec
* add stu3 template package
=> Hotfix (#390)

Directory.Build.props, GeoPol.xml, README.md, docs/HL7v2-FHIRValidator.md, docs/HL7v2-ImportantPoints.md, docs/HL7v2-templates.md, release.yml, src/Microsoft.Health.Fhir.Liquid.Converter/Microsoft.Health.Fhir.Liquid.Converter.csproj, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.Liquid.Converter.nuspec, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.TemplateManagement.csproj
Merge latest ```main``` branch (handle some conflicts)
The ```dotliquid``` and ```main``` is different, because some pull requests are directly merged into ```main``` so ```dotliquid``` is out of date.
=> Merge latest main into dotliquid

release.yml
=> Update version to 5.0.4

release.yml
=> Update version to 5.0.5

release.yml, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Processors/ProcessorTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestData/Expected/ExamplePatient.json, src/Microsoft.Health.Fhir.Liquid.Converter/Parsers/JsonDataParser.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Processors/JsonProcessor.cs
=> Prepare new release for 5.0.5

src/Microsoft.Health.Fhir.TemplateManagement/ArtifactProviders/TemplateCollectionProvider.cs
When we fetch the convert templates for the first time, or when the template cache expires, there is nothing stopping multiple threads from pulling images (templates) from the ACR. This means that if we receive a lot of convert requests at the same time (for example 200+) and the templates are not cached, then almost each one of these convert requests will attempt to pull the image from the ACR. The number of requests generated will result in a denial of service and eventually attempts to the ACR will be blocked, which results in $convert returning an HTTP 500 status code.
In this PR we modify the code so that at most only one thread can pull any image from the ACR. This will ensure that the first request pulls from the ACR and the rest pull from the cache. After the image is cached we …
=> Limit the number of threads that can pull from ACR at the same time

release.yml, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests.csproj, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Microsoft.Health.Fhir.Liquid.Converter.UnitTests.csproj, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Microsoft.Health.Fhir.TemplateManagement.UnitTests.csproj, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Providers/BlobTemplateProviderTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/ArtifactProviders/BlobTemplateProvider.cs, src/Microsoft.Health.Fhir.TemplateManagement/ArtifactProviders/IConvertDataTemplateProvider.cs, src/Microsoft.Health.Fhir.TemplateManagement/Factory/ITemplateProviderFactory.cs, src/Microsoft.Health.Fhir.TemplateManagement/Factory/StorageTemplateProviderFactory.cs, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.TemplateManagement.csproj
Adds classes and interfaces to support reading convert templates from a storage container
=> Support reading convert templates from a storage container

data/Templates/Hl7v2/Resource/_MedicationRequest.liquid, data/Templates/Hl7v2/Resource/_SupplyRequest.liquid
The current implementation of RDE feed conversion is encountering a failure due to incorrect referencing of ID/PractitionerRole template.
Updated template for every reference of ID/PractitionerRole, resolving the conversion failure.
Using [Fhir Converter sample](https://github.com/microsoft/FHIR-Converter/blob/main/data/SampleData/Hl7v2/RDE-O11-01.hl7)
POST azure-server/$convert-data
<details>
<summary>Body</summary>
```json
{
"resourceType": "Parameters",
"parameter": [
{
"name": "rootTemplate",
"valueString": "RDE_O11"
},
{
"name": "templateCollectionReference",
"valueString": "microsofthealth/fhirconverter:default"
},
{
"name": "inputData",
"valueString": "MSH|^~\\&|IMMAPP|GHHSFacility^2.16.840.1.122848.1.30^ISO|EHRApp^1.Edu^ISO|GHHRFacility^2.16.840.1.1122848.1.32^ISO|202108181126+0215 …
```
=> Fix template references for Id/PractitionerRole (case sensitive)

src/Microsoft.Health.Fhir.Liquid.Converter/Processors/BaseProcessor.cs
Fix the typo bug in the logging.
=> Fixing the bug in the logging.

docs/how-to-guides/customize-templates.md
Add information about custom templates
=> Add information about custom templates

docs/how-to-guides/troubleshoot.md
=> Add additional error codes

docs/TemplateManagementCLI.md
Re-add TemplateManagementCLI.md previously removed because of external references.
=> Re-add TemplateManagementCLI.md because of external references.

.config/tsaoptions.json, CredScanSuppressions.json, build/.vsts-ci.yml, build/.vsts-pr.yml, build/analyze.yml, build/build.yml
Adding an 'analyze' stage to perform CG and other security tasks
=> Initial commit of cg analysis code
