src/lib/fsCache/cache.js
As per mkdir spec, mkdir shouldn't throw EEXIST if recursive:true option is provided. But it seems it fails for some specific version. So adding check to ignore this error if that happens.  
Tested manually to a machine which reported the issue.
=> ignore mkdir EEXIST error

src/lib/hl7v2/hl7v2.js, src/lib/workers/worker.js, src/routes.spec.js
fix the error returned when parsing fails. Bug was caused due to incorrect assumption on the err object.
fix the error returned when parsing fails. Bug was caused due to incorrect assumption on the err object.
Addresses #74409
unit tests and manual testing.
=> fix the error returned when parsing fails

src/lib/handlebars-converter/handlebars-helpers.js
Story:
V2 templates were released earlier than the CCDA templates. some customers may already be using it,  so we want to protect the V2 behavior. Changing the behavior will break their templates and they will have to re-write those.
The cause of bug:
In version 2.0, I found that the helpers 'eq' and 'ne' have been modified. They are changed from equality operator ('==') to strong equality operator  ('==='), inequality operator ('!=') to strong inequality operator ('!=='). Strong equality operator returns true only when the type and value are the same, so when the types are different, false will be returned. Therefore, for the case in bug 74581, when we only use '"status":{{>DataType/_string.hbs mapping="CodeSystem/ResultStatus.hbs" inCode=OBR-25 }}' in the template …
=> revert eq/ne helpers due to the bug 74581

src/lib/handlebars-converter/handlebars-helpers.js
Add a check for an empty templateId in the getFirstCdaSectionsByTemplateId helper.
Addresses [issue #54].
Manually tested with CCD that has sections with missing template Ids.
=> Add check for missing template Id

src/lib/handlebars-converter/handlebars-helpers.js
Revert the generateUUID function until the impact on users is clear.
**Currently the NodeJS CI will not pass, but will be solved soon.**
=> 2020.09.01 revert generateUUID function

src/routes.js
The Swagger doc was not correct, and therefor "try it out" in the browser also didn't work. 
This fixes the problem in the jsdoc by documenting the `srcDataType` field.
=> Fix swagger documentation

src/static/js/template-editor.js
This issue occurs because the editor will remove all the non-latin characters to fit with the `window.btoa` function.
There is an easy way to accept utf8 characters using nested functions, see [here](https://stackoverflow.com/questions/18729405/how-to-convert-utf8-string-to-byte-array/18729931).
Addresses [issue #78 ].
All unittests are passed.
=> 2020.10.12 solved issue #78

test/e2e-test/rule-test/util/test-rule-functions.js
Patching for the previous pull request.
**The teriminology server of java validator** was down just before merging. So the CI can't pass in the master branch (but it goes well before merging, or to say before the terminology server crashing). I modified the validator logic to omit touching remote terminology server.
All tests and CI passed.
=> 2020.10.20 fixed the terminology server connection issue inside the java validator

src/routes.js
The @swagger header for the `/api/templates/{file}` path was incorrect.  The parameter `name` and the body had some missing information.
Addresses #88.
It was impossible to validate the swagger file generated when getting `api-docs.json`.  After this change, I could validate and and use it for server stub generation.
=> fix: added `type` to param file and `schema` to body

README.md, docs/SnippetConcept.md, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/FunctionalTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.Tool/ConverterLogicHandler.cs, src/Microsoft.Health.Fhir.Liquid.Converter.Tool/Models/ConverterOptions.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Filters/SegmentFiltersTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Hl7v2ProcessorTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/SafeListTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Hl7v2/Hl7v2Processor.cs, src/Microsoft.Health.Fhir.Liquid.Converter/IFhirConverter.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Models/FhirConverterErrorCode.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Resources.Designer.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Resources.resx, src/Microsoft.Health.Fhir.Liquid.Converter/SafeList.cs
- Update command-line option from `-e` to `-r` and rename `entryTemplate` to `rootTemplate` according to discussion in PR #94.
- Refine several tests.
=> Rename entryTemplate to rootTemplate

docs/template-creation-how-to-guide.md
Fixes broken links in the template creation guide.
Verified that the updated links in the template creation guide are working as expected and link to the correct pages.
=> fix broken links in template creation guide

src/Microsoft.Health.Fhir.Liquid.Converter/DotLiquids/MemoryFileSystem.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Utilities/TemplateUtility.cs
Move evaluate tag registration in `TemplateUtility`. We need to register this tag before `Template.ParseHl7v2Templates()` is called. In template management, it is called before creating `ITemplateProvider`.
=> [DotLiquid] Move evaluate tag registration in TemplateUtility

src/Microsoft.Health.Fhir.Liquid.Converter.Tool/Program.cs
Fix command-line options. The tool should not return "Process failed:" when input option is `help` or `version`. ([ref](https://github.com/commandlineparser/commandline/blob/master/src/CommandLine/HelpTextExtensions.cs))
=> [DotLiquid] Fix command-line options

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/EvaluateTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/MemoryFileSystemTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/TemplateLocalFileSystemTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Hl7v2TemplateProviderTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter/DotLiquids/MemoryFileSystem.cs, src/Microsoft.Health.Fhir.Liquid.Converter/DotLiquids/TemplateLocalFileSystem.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Hl7v2/Hl7v2Processor.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Hl7v2/Hl7v2TemplateProvider.cs, src/Microsoft.Health.Fhir.Liquid.Converter/IFhirConverterTemplateFileSystem.cs, src/Microsoft.Health.Fhir.Liquid.Converter/ITemplateProvider.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Utilities/TemplateUtility.cs
When templates are loaded from local file system, the engine could load them gradually when they are used, instead of loading them at once from beginning. This helps improve the performance in VS Code extension.
=> [DotLiquid] Refine template loading performance

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Models/Hl7v2TraceInfoTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Hl7v2/Models/Hl7v2TraceInfo.cs
* MSH segments should be treated separately 'cause the first `|` is a special field, which caused incorrect indexing.
* Updated related test cases.
Well, we can't put the grammar escaping in post processing phase 'cause the `rawResult` contains tons of `"` to constrcut JSON result, the grammar escaping will mistakenly escape them, which causes error.
And we can't put the semantical unescaping in post processing phase 'cause the semantical unescaping must be done before grammar escaping, or some semantically escaped content(`\T\`, \E\) will be mistakenly grammar escaped(to `\\T\\`, `\\E\\`).
So we currently can only keep the semantical unescaping and grammar escaping in `NormalizeText`, and let the indexing offset by some spaces if the origin message contains semantically escapped …
=> Fixed trace info indexing issue for MSH segments while generating unused segments

data/Templates/Hl7v2/ADT_A01.liquid, data/Templates/Hl7v2/OML_O21.liquid, data/Templates/Hl7v2/ORU_R01.liquid, data/Templates/Hl7v2/Resource/_Encounter.liquid, data/Templates/Hl7v2/Resource/_Patient.liquid, data/Templates/Hl7v2/Resource/_PractitionerRole.liquid, data/Templates/Hl7v2/Resource/_Procedure.liquid, data/Templates/Hl7v2/VXU_V04.liquid, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-28-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-251-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-28-expected.json
* All changed resource templates: `Encounter`, `PractitionerRole` and `Procedure`.
* All main templates are changed.
* Changed the ID from `generateUUID ...` to a ID variable passed by the invoker(usually the main templates).
* Changed the main templates to pass the referred ID.
* BTW, the reason why we directly set reference attributes inside resource templates instead of invoking `include Reference/.../...` is that if a resource has multiple reference attributes with the same type, there will be no way to tell them, like `PV1-3, Location.Reference` and `PV1-6, Location.Reference`.
=> Fix the handlebars-style reference ID in resource templates

data/Templates/Hl7v2/ADT_A01.liquid, data/Templates/Hl7v2/OML_O21.liquid, data/Templates/Hl7v2/ORU_R01.liquid, data/Templates/Hl7v2/VXU_V04.liquid, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT01-28-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-23-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-251-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ADT_A01/ADT04-28-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/OML_O21/MDHHS-OML-O21-1-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/OML_O21/MDHHS-OML-O21-2-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LAB-ORU-1-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LAB-ORU-2-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/LRI_2.0-NG_CBC_Typ_Message-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/ORU_R01/ORU-R01-RMGEAD-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/VXU_V04/IZ_1_1.1_Admin_Child_Max_Message-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/VXU_V04/VXU-expected.json
* Change the templates so that the default bundle type is 'batch' instead of 'transaction' because our FHIR servers do not support 'transaction' yet.
=> Change resource bundle type from 'transaction' to 'batch'

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/EvaluateTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Hl7v2/Hl7v2Processor.cs
Avoid using Hash.FromAnonymousObject since it creates a temporal name for input data type. This may cause potential errors when used in difference context, such as creating Hash object from different dlls.
=> Replace Hash.FromAnonymousObject with Hash.FromDictionary

README.md
The handle bar engine moved to a dedicated branch but the instructions in the README did not get updated.
Running `npm install` on main branch triggers the following wrarnings.
```
npm WARN saveError ENOENT: no such file or directory, open '/Users/tnegri/work/FHIR-Converter/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/tnegri/work/FHIR-Converter/package.json'
npm WARN FHIR-Converter No description
npm WARN FHIR-Converter No repository field.
npm WARN FHIR-Converter No README data
npm WARN FHIR-Converter No license field.
up to date in 0.705s
found 0 vulnerabilities
```
I believe the new instructions should be:
```
git clone https://github.com/microsoft/FHIR-Converter/
cd FHIR-Converter
git checkout handlebars
npm install
npm start
```
=> update on-prem instruction for the handlebars README

data/Templates/Hl7v2/ADT_A01.liquid, data/Templates/Hl7v2/OML_O21.liquid, data/Templates/Hl7v2/ORU_R01.liquid, data/Templates/Hl7v2/Resource/_Condition.liquid, data/Templates/Hl7v2/Resource/_DiagnosticReport.liquid, data/Templates/Hl7v2/Resource/_Encounter.liquid, data/Templates/Hl7v2/Resource/_Immunization.liquid, data/Templates/Hl7v2/Resource/_Observation.liquid, data/Templates/Hl7v2/Resource/_Patient.liquid, data/Templates/Hl7v2/Resource/_PractitionerRole.liquid, data/Templates/Hl7v2/Resource/_Provenance.liquid, data/Templates/Hl7v2/Resource/_ServiceRequest.liquid, data/Templates/Hl7v2/VXU_V04.liquid, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/OML_O21/MDHHS-OML-O21-2-expected.json, src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/TestData/Expected/Hl7v2/VXU_V04/VXU-expected.json
* Move reference ID evaluation statements inside resource tempaltes to simplify usage.
* Performance test results are [here](https://microsoftapc.sharepoint.com/:f:/t/CompassTeam/Ep-xcAK04zpCgv9U1f0OIfIBeJLzeDbrwIXFJapycOSrdA?e=5m55PY). The total performance is slightly improved.
=> Move reference ID evaluation statements inside resource tempaltes to simplify usage

README.md, src/Microsoft.Health.Fhir.Liquid.Converter.Tool/ConverterLogicHandler.cs, src/Microsoft.Health.Fhir.Liquid.Converter.Tool/Models/ConverterOptions.cs
For VS Code extension, the C-CDA input files are too large to be passed as command-line argument, so we add a file-to-file conversion option.
=> Add file-to-file option in command-line tool

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Ccda/CcdaDataParserTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Ccda/CcdaTemplateProviderTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/EvaluateTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/TemplateLocalFileSystemTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Filters/SectionFiltersTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Filters/SegmentFiltersTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Hl7v2DataParserTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Hl7v2TemplateProviderTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Hl7v2/Models/Hl7v2TraceInfoTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/ProcessorTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestConstants.cs, src/Microsoft.Health.Fhir.Liquid.Converter/BaseProcessor.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Ccda/CcdaDataParser.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Ccda/CcdaProcessor.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Constants.cs, src/Microsoft.Health.Fhir.Liquid.Converter/DotLiquids/IFhirConverterTemplateFileSystem.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Filters/CollectionFilters.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Hl7v2/Hl7v2DataParser.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Hl7v2/Hl7v2Processor.cs
Make all parsers return same data structure `IDictionary<string, object>` by moving logics for Hl7 v2 from `BaseProcessor` to `Hl7v2DataParser` in converter engine. Only code refinements and no behavior change.
Some other refinements:
- Add `Constants.cs` to hold constant keys for parsers
- Rename `Constants.cs` in unit tests to `TestConstants.cs`
- Refine namespace for `IFhirConverterTemplateFileSystem`
=> Make all parsers return same data structure in converter engine

release.yml, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.Liquid.Converter.nuspec, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.TemplateManagement.csproj
Remove RestSharp, which has a component governance alert of current version, and is never used in our repo.
=> Remove unused library

release.yml, src/Microsoft.Health.Fhir.TemplateManagement.FunctionalTests/TemplateCollectionFunctionalTests.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Models/DefaultTemplateInfoTest.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Models/ImageInfoTest.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Providers/TemplateCollectionProviderTests.cs, src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/TemplateCollectionProviderFactoryTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.TemplateManagement.csproj, src/Microsoft.Health.Fhir.TemplateManagement/Models/DefaultTemplateInfo.cs
By discussion, we are going to pack the sample templates as default templates for JSON converter. This PR (1) packs the templates and (2) updates the version in release pipeline.
=> Add support for JSON default templates

release.yml
Notice generation will only be triggered when targeting main branch.
=> Add condition for notice generation

src/Microsoft.Health.Fhir.Liquid.Converter.FunctionalTests/RuleBasedTests.cs
Currently, we run FHIR validator in CI but it is not required to pass. As we are having a lot more test cases to run with new templates coming, this takes longer time than expected (more than 1 hour). So we skip running it in pipeline.
=> Skip FHIR validator tests

package.json
* For the [handlebars](https://www.npmjs.com/package/handlebars) package, we use a more specific way to declare the version number;
* For the [ajv](https://www.npmjs.com/package/ajv) package, currently we don't upgrade it since:
* The most elegant way to do that is to use the `overrides` property, which is available from NPM [version 8.3](https://github.com/npm/cli/releases/tag/v8.3.0)
* We don't want to restrict the version of NPM, especially such a new version
* The `ajv` is actually indirectly referenced by `eslint` and `nodegit`, which we are actually not using in production environment
=> Fix down the smallest version of handlebars, upgrade defective packages

release.yml
Turn on mac functional test check, so we don't have to look into it manually every time when the pipeline runs.
=> Turn on mac functional test check

GeoPol.xml
File was deleted recently possibly in the move to main from master - I think by a checkin from deepak-ms
=> Global Readiness Manifest file GeoPol.xml

GeoPol.xml
Remove the `test` folder in path to exclude since it no longer exists in this repo.
=> Remove invalid folder configuration in GeoPol file

Directory.Build.props
- Fix build-time dependency on `StyleCop.Analyzers` to no longer force consumers to use the same analyzers
=> Fix StyleCop Dependency

src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.Liquid.Converter.nuspec
- Remove StyleCop from the nuspec to prevent forcing consumers to import StyleCop
- This is a continuation of the previous PR: https://github.com/microsoft/FHIR-Converter/pull/397
- I had not realized there was also an explicit .nuspec file
=> Remove StyleCop from Nuspec

data/Templates/Json/Schema/meta-schema.json, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/TemplateLocalFileSystemTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/DotLiquids/ValidateTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestData/TestTemplates/InvalidValidateTemplates/Schemas/InvalidTestSchema.schema.json, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestData/TestTemplates/ValidValidateTemplates/Schemas/TestSchema.schema.json, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestData/TestTemplates/ValidValidateTemplates/Schemas/TestSchema2.schema.json, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestData/TestTemplates/ValidValidateTemplates/Schemas/TestSubPropertySchema.schema.json, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestData/TestTemplates/ValidValidateTemplates/ValidUnmatchedTemplate3.liquid, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Utilities/TemplateUtilityTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter/DotLiquids/Validate.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Microsoft.Health.Fhir.Liquid.Converter.csproj, src/Microsoft.Health.Fhir.Liquid.Converter/Models/Json/JSchemaContext.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Models/Json/JSchemaDocument.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Models/Json/JSchemaTraceInfo.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Processors/JsonProcessor.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Utilities/TemplateUtility.cs, src/Microsoft.Health.Fhir.TemplateManagement.FunctionalTests/TemplateCollectionFunctionalTests.cs
Change the json schema lib to [NJsonSchema](https://github.com/RicoSuter/NJsonSchema) to avoid the validate count limit.
=> Change to NJsonSchema lib

src/Microsoft.Health.Fhir.TemplateManagement/Microsoft.Health.Fhir.Liquid.Converter.nuspec
The released Nuget package misses ```NJsonSchema``` dependency, add it to Nuspec file.
=> Add NJsonSchema dependency to nuspec file

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Processors/ProcessorTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/TestData/Expected/ExamplePatient.json, src/Microsoft.Health.Fhir.Liquid.Converter/Parsers/JsonDataParser.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Processors/JsonProcessor.cs
Add interface in ```JsonProcessor``` to directly convert ```JObject``` instance.
The target is to decrease the serialization count to improve the performance in Synapse pipeline.
=> JsonProcessor interface to convert JObject

src/Microsoft.Health.Fhir.Liquid.Converter.Tool/ConverterLogicHandler.cs
When output file has no directory present like "1.txt", the tool will throw exception that it cannot create an empty directory.
=> Fix empty path issue

release.yml
The ADO pipeline to run MacOS functional tests has not been running due to the lack of a functional Mac agent to run the tests on. Disabling this step until there is an appropriate hosted Mac agent to run the tests.
=> Disable MacOS functional tests in release pipeline

src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Providers/BlobTemplateProviderTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/ArtifactProviders/BlobTemplateProvider.cs
Bug: When no templates are provided, template collection returned is not empty but a list containing an empty dictionary item.
Fix: If no templates are parsed, the template collection returned should be empty.
=> fix: Template collection parsed should be empty when no blob templates provided.

nuget.config
Update nuget config to single feed for secure supply chain. 
Remove nuget.org feed since it is included in the Microsoft Health OSS feed.
=> Update nuget config to single feed

src/Microsoft.Health.Fhir.Liquid.Converter/Factories/ConvertProcessorFactory.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Factories/IConvertProcessorFactory.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Models/ConvertDataOutputFormat.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Models/ConvertTelemetryConfiguration.cs
Adds ConvertProcessFactory to return the correct implementation of IFhirConverter depending on the input and output dataTypes.
=> Add ConvertProcessorFactory

data/Templates/Hl7v2/Resource/_Patient.liquid
The `_Patient.liquid` template includes two `meta` sections. This PR combines the two sections.
=> fix: remove duplicate meta section from _Patient

src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Factory/ConvertDataTemplateCollectionProviderFactoryTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/Factory/ConvertDataTemplateCollectionProviderFactory.cs
Currently, if containerUrl is empty, the factory attempts to create blob template provider and throws on null containerUrl. 
Instead it will be better to use default template provider and not throw on initialization.
=> Use default template provider if containerUrl is empty

src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Providers/BlobTemplateCollectionProviderTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/ArtifactProviders/BlobTemplateCollectionProvider.cs, src/Microsoft.Health.Fhir.TemplateManagement/Configurations/StorageAccountConfiguration.cs, src/Microsoft.Health.Fhir.TemplateManagement/Configurations/TemplateHostingConfiguration.cs, src/Microsoft.Health.Fhir.TemplateManagement/Exceptions/TemplateCollectionExceedsSizeLimitException.cs, src/Microsoft.Health.Fhir.TemplateManagement/Models/TemplateManagementErrorCode.cs
Check blob template collection is within the max size limit (10MB) to constrain template sizes.
=> Blob template collection size limit restriction

docs/deploy/Deploy-DependentResources.bicep
Disable shared key access for storage accounts.
https://learn.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=template.
MI is used to access storage accounts.
=> Disable shared key access for storage accounts

data/Templates/Stu3ToR4/DetectedIssue.liquid, data/Templates/Stu3ToR4/Immunization.liquid
#562 causes datetime values in the input to be treated as strings. This preserves the original data and allows it to be passed as-is to the Liquid engine. Previously the behavior created .Net dateTime objects which were then passed to the rendering engine. Functions such as `date` respond differently when presented with a `string` or `dateTime` object. This difference is causing the `date` function to convert the string to local datetime and is causing the unit test to fail.
This PR removes the use of  the `date` function from within the test template. Since the value is already a properly formatted datetime string (versus a .net datetime object) this function is no longer needed.
=> Remove date parsing when input value is string

src/Microsoft.Health.Fhir.TemplateManagement.UnitTests/Providers/BlobTemplateCollectionProviderTests.cs, src/Microsoft.Health.Fhir.TemplateManagement/ArtifactProviders/BlobTemplateCollectionProvider.cs
Bug: With some recent package updates, empty blobs are being returned as null instead of empty causing the download to fail.
Fix: Read as byte array and then get encoded string. This handles empty byte array and returns empty string.
=> Fix blob download for empty blobs

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Filters/CollectionFiltersTest.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Filters/CollectionFilters.cs
Add custom filter to process batch of resources in parallel
=> Add custom filter to process batch of resources in parallel

src/Microsoft.Health.Fhir.Liquid.Converter.UnitTests/Filters/SegmentFiltersTests.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Filters/SegmentFilters.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Models/FhirConverterErrorCode.cs, src/Microsoft.Health.Fhir.Liquid.Converter/Processors/BaseProcessor.cs
In this PR I handle a case where a template calls a Filter that expects hl7 data but what was passed in was fhir. So, in this case there is no hl7 passed in and it fails with a generic message (ie Internal server error with 500) in the convert. This change is needed so that in convert we can catch this specific case and respond with a better message.
=> Better handling of a template data mismatch error case
